from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.0.0")


##### setup report #####
configfile: "config/config.yaml"
# 
# 
# report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"

##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/align.smk"
include: "rules/filter.smk"
include: "rules/hybrid_ase.smk"
include: "rules/bigwigs.smk"
include: "rules/diff_exp.smk"

##### target rules #####
rule all:
    input:
        
        # featureCounts outputs
        "results/hybrid_ase/counts/concat_featureCounts_unique.txt",
        "results/hybrid_ase/counts/concat_featureCounts_multi_fraction.txt",

        # raw individual bigWigs
        expand(
            "results/hybrid_ase/bigwigs/multimapper_inclusive/{sample_name}.bw",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_ase/bigwigs/unique_only/{sample_name}.bw",
            sample_name=samples.index
        ),

        # z-score normalized individual bigWigs
        expand(
            "results/hybrid_ase/bigwigs_zscore/multimapper_inclusive/individual/{sample_name}.bw",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_ase/bigwigs_zscore/unique_only/individual/{sample_name}.bw",
            sample_name=samples.index
        ),

        # z-score normalized merged bigWigs
        expand(
            "results/hybrid_ase/bigwigs_zscore/multimapper_inclusive/merged/{sample_group}.bw",
            sample_group=sorted(samples["condition"].unique())
        ),
        expand(
            "results/hybrid_ase/bigwigs_zscore/unique_only/merged/{sample_group}.bw",
            sample_group=sorted(samples["condition"].unique())
        )
