from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.0.0")


##### setup report #####
configfile: "config/config.yaml"
# 
# 
# report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"

##### load rules #####
include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/align.smk"
include: "rules/filter.smk"
include: "rules/hybrid_ase.smk"
include: "rules/bigwigs.smk"
include: "rules/diff_exp.smk"

##### target rules #####
rule all:
    input:
        get_final_output(),
        "results/hybrid_ase/counts/concat_featureCounts.txt",
        "results/hybrid_ase/snps/diagnostic_mel_sim_snps.vcf.gz",
        expand(
            "results/hybrid_ase/allele_counts/{sample_name}.diagnostic_sites.bcf",
            sample_name=samples.query("ase_role == 'hybrid'").index
        ),
        expand(
            "results/hybrid_ase/bigwigs/multimapper_inclusive/{sample_name}.bw",
            sample_name=samples.index
        ),
        expand(
            "results/hybrid_ase/bigwigs/unique_only/{sample_name}.bw",
            sample_name=samples.index
        )
